[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_PATHS = "scripts"

[context.production]
  command = "npm run build"
  publish = "build"

[context.deploy-preview]
  command = "npm run build"
  publish = "build"

[context.branch-deploy]
  command = "npm run build"
  publish = "build"
